// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3045_002_finalapiproject_smmk.Data;

#nullable disable

namespace _3045_002_finalapiproject_smmk.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120024713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_3045_002_finalapiproject_smmk.Models.Pet", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetID"));

                    b.Property<bool>("Adopted")
                        .HasColumnType("bit");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetID");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetID = 1,
                            Adopted = true,
                            Age = 3,
                            PetName = "Buddy",
                            Type = "Dog"
                        },
                        new
                        {
                            PetID = 2,
                            Adopted = false,
                            Age = 2,
                            PetName = "Whiskers",
                            Type = "Cat"
                        },
                        new
                        {
                            PetID = 3,
                            Adopted = true,
                            Age = 1,
                            PetName = "Goldie",
                            Type = "Fish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
